name: Actions Workflow

on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Sinple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat is greeted'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: List files
        run:  |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files After checkout
        run:  |
          ls -a
          cd .github
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"_